### ISSUE TITLE
error at line 78     def _run(library: pd.DataFrame, feature_ref_path: str, transcriptome_path, localcores, localmem,

### ISSUE THREAD

**Issue by nbutyrate** [keshav-motwani/multisampleranger#1]
HI I am trying to run cell-ranger on > 24 samples, 

attached are my batch file and the library file and the script and following is the error

 File "./count.py", line 78
    def _run(library: pd.DataFrame, feature_ref_path: str, transcriptome_path, localcores, localmem,
                    ^
SyntaxError: invalid syntax

please let me know what is wrong with my workflow

[easy_ranger_files.zip](https://github.com/keshavmot2/easyranger/files/4161016/easy_ranger_files.zip)

**Comment by keshavmot2** [comment]
Hi nbutyrate,

Thanks for your interest in easyranger! 

There's a few problems I see: this particular error seems to be coming from the fact that you're likely defaulting to the python 2.x interpreter instead of a python3 one. To fix this, simply add python3 before ./count.py.

Additionally, your fastq_pattern doesn't look correct. The `PREFIX` and `SUFFIX` thing were there just to indicate stuff can go before or after. I'd imagine it should be `/home/sangwan/isilon/Angela/SCRRNA/BL/<library_name>/`

One more thing, your file is actually named `library.txt`, but you refer to it as `libraries.txt`. Originally I was only supporting comma separated files, but I updated it to allow for tab separated as well, so it should work fine.

In summary, your call should look like:

`python3 source/count.py --libraries_path library.txt --transcriptome /home/sangwan/isilon/Angela/GRCh38_and_mm10 --fastq_pattern "/home/sangwan/isilon/Angela/SCRRNA/BL/<library_name>/" --localmem 200 --localcores 20`

Assuming that `library.txt` is in the same folder as easyranger. 

I was working on several bug fixes and feature additions, so please pull from the master before running this again.

I have also added support to be able to run the multiple samples as a SLURM array job. I am doing some final testing with this,  and will update documentation today with this information. This has the advantage of letting the SLURM manager schedule the jobs as resources are available, and in practice speeds up the process significantly. 

Also, may I ask if this is a "barnyard" experiment, with cells from both mouse and human? If so, the transcriptome reference looks fine, but if not, you should only be mapping to either GRCh38 or mm10, depending on your species.

Let me know if any issues! I really appreciate your patience with this as the tool is very much still in a developmental stage.

Best,
Keshav

**Comment by nbutyrate** [comment]
Thanks for the help Keshav,

i did changes as you suggested, here is the curent error from stdout file

(base) [sangwan@cc-dclrilog52 EasyRanger]$ cat count.stdout 
Traceback (most recent call last):
  File "./count.py", line 8, in <module>
    from source.utils.path_manager import PathManager
ImportError: No module named 'source'

**Comment by keshavmot2** [comment]
Did you pull the latest master branch? I made some changes earlier that should resolve this (`sys.path.extend([os.path.abspath(__file__ + "/../../")])` in count.py).

Let me know if even with the latest branch it is throwing this error. If so, try adding `export PYTHONPATH="XXX"` where XXX is the path to the easyranger repository. 

Best,
Keshav

**Comment by nbutyrate** [comment]
I just tried to do the same, its showing same error, please review the attached files and let me know if i am doing smth incorrect
[new_files.zip](https://github.com/keshavmot2/easyranger/files/4166154/new_files.zip)

**Comment by keshavmot2** [comment]
In these files, you are only including the `count.py` file. Is this all that is in your directory, or did you clone the entire repository? Cloning the repository is required, as helper functions outside of `count.py` are used. 

Please make sure you've cloned the respository by running 
```
git clone https://github.com/keshavmot2/easyranger.git
cd easyranger
```

**Comment by nbutyrate** [comment]
i cloned the latest i repeated the workflow now its showing

Traceback (most recent call last):
  File "./count.py", line 8, in <module>
    from source.utils.path_manager import PathManager
  File "/mnt/isilon/data/w_cores/MicrobialCompositionandAnalyticsCore/Angela/easyranger/source/utils/path_manager.py", line 1, in <module>
    from pathlib import Path
ImportError: No module named 'pathlib'

**Comment by keshavmot2** [comment]
Can you run the following to tell me your python3 version?

```
python3
import sys
print(sys.version)
```

I think pathlib is only in versions 3.4 or greater, so you may need to upgrade to this if your python version is older than this.

Also ensure that you are running `python3 source/count.py ...`, with `python3` in the front.

**Comment by nbutyrate** [comment]
I did all teh changes here is the current error, looks like i need to format my libraries.csv file? but i think my file already has that column (enclosing the file here(changed the extension from .csv to text to upload here)
[libraries.txt](https://github.com/keshavmot2/easyranger/files/4166925/libraries.txt)
)

 File "./count.py", line 153, in <module>
    Count.main()
  File "./count.py", line 39, in main
    args.result_path)
  File "./count.py", line 64, in run
    Count.check_libraries(libraries, fastq_pattern)
  File "./count.py", line 139, in check_libraries
    Count.SAMPLE_NAME + " column must be present in libraries file"
AssertionError: sample_name column must be present in libraries file

**Comment by keshavmot2** [comment]
That's weird, that was happening on old versions when I didn't support tab separated, but now either comma or tab should work. 

I've updated it and added a more useful error message perhaps. It won't resolve the issue, but will help me debug the issue. 

Can you pull from the master and then rerun and send me the error?

In the easyranger directory, run:
```
git pull
```

Then rerun the easyranger command.

Thanks again for your patience with this!
Keshav

**Comment by keshavmot2** [comment]
Oh, it was an encoding issue... there was a "\ufeff" in the "sample_name" column... go ahead and pull as I mentioned above and rerun, it should hopefully work fine now.

**Comment by nbutyrate** [comment]
File "./count.py", line 153, in <module>
    Count.main()
  File "./count.py", line 39, in main
    args.result_path)
  File "./count.py", line 68, in run
    PathManager.create_path(result_path + "/" + Count.OUTPUT_PATH)
  File "/mnt/isilon/data/w_cores/MicrobialCompositionandAnalyticsCore/Angela/easyranger/source/utils/path_manager.py", line 10, in create_path
    path.mkdir(parents=True, exist_ok=True)
TypeError: mkdir() got an unexpected keyword argument 'exist_ok'

**Comment by keshavmot2** [comment]
I know I've mentioned this several times, but are you writing the command starting with `python3`? That error indicates you might still be running it using python2... 

https://github.com/bamos/dcgan-completion.tensorflow/issues/20

**Comment by keshavmot2** [comment]
Assuming the file paths here are correct, the command you run should look like:

```
python3 source/count.py --libraries_path /home/keshav.motwani/libraries.txt --transcriptome /home/sangwan/isilon/Angela/GRCh38_and_mm10 --fastq_pattern "/home/sangwan/isilon/Angela/SCRRNA/BL/<library_name>/" --localmem 200 --localcores 20
```

**Comment by nbutyrate** [comment]
when i am running following batch file

#SBATCH --error=count.stdout
#SBATCH --output=count.stderr
PYTHONPATH="/cm/shared/apps/cellranger/3.1.0/cellranger-cs/3.1.0/"

module load cellranger/3.1.0

module load python/3.3.5

python3 ./count.py --libraries_path libraries.csv --transcriptome /home/sangwan/isilon/Angela/GRCh38 --fastq_pattern /home/sangwan/isilon/Angela/SCRRNA/BL/library_name/ --result_path /home/sangwan/isilon/Angela/SCRRNA/BL/ --localmem 700 --localcores 20



it shows me the following error

/cm/local/apps/slurm/var/spool/job667041/slurm_script: line 16: python3: command not found

**Comment by keshavmot2** [comment]
Change `module load python/3.3.5` to `module load python3` maybe? 

If your HPC is anything like ours here at UF that should work and load the latest version of python3. That's not really a question for me though, that's a question for your HPC team.

**Comment by keshavmot2** [comment]
Also, your `fastq_pattern` is still wrong, please use the one I sent above:

`/home/sangwan/isilon/Angela/SCRRNA/BL/<library_name>/`

There needs to be brackets around the library name.

**Comment by nbutyrate** [comment]
admin told me to use python3.3

i ran the following

module load python/3.3.5

python3.3 ./count.py --libraries_path libraries.csv --transcriptome /home/sangwan/isilon/Angela/GRCh38 --fastq_pattern /home/sangwan/isilon/Angela/SCRRNA/BL/<library_name>/ --result_path /home/sangwan/isilon/Angela/SCRRNA/BL/ --localmem 700 --localcores 20

now it threw

/cm/local/apps/slurm/var/spool/job667144/slurm_script: line 16: library_name: No such file or directory

**Comment by keshavmot2** [comment]
The fastq pattern must be in quotes, like the command I sent above. 

It might not work with python 3.3... pathlib was introduced in 3.4, and is currently required by easyranger.

**Comment by keshavmot2** [comment]
Hi nbutyrate,

Were you able to resolve the issue with the above?

Best,
Keshav
